language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - pip install six
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
      pip install unittest2
      pip install argparse
    fi
  - python setup.py develop
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
      unit2 discover -v
    else
      python -m unittest discover -v
    fi
notifications:
  email:
    - dickinsm@gmail.com
